title: Burhanuddin Irsyad
description: Data Scientist | Data Analyst | Data Engineer

url: "https://burhan.github.io"
baseurl: ""

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

show_downloads: false

github:
  is_project_page: false

markdown: kramdown
